Repository SimpleStepSolutions/keycloak-http, pull requests merged in 2019-06, with the labels that each got.

#1 change name
  charts/keycloak-http/values.yaml
Labels: size/XS

#4 Pr upgrade test
  charts/keycloak-http/files/bbd-realm.json
  charts/keycloak-http/files/external-realm.json
  charts/keycloak-http/files/master-realm.json
  charts/keycloak-http/requirements.yaml
  charts/keycloak-http/templates/realm-secret.yaml
  charts/keycloak-http/values.yaml
Labels: approved, size/XXL

#5 Revert "Revert "try realms""
  charts/keycloak-http/files/bbd-realm.json
  charts/keycloak-http/files/external-realm.json
  charts/keycloak-http/files/master-realm.json
  charts/keycloak-http/templates/realm-secret.yaml
  charts/keycloak-http/values.yaml
Labels: size/XXL

#6 Revert "Revert "Revert "try realms"""
  charts/keycloak-http/files/bbd-realm.json
  charts/keycloak-http/files/external-realm.json
  charts/keycloak-http/files/master-realm.json
  charts/keycloak-http/templates/realm-secret.yaml
  charts/keycloak-http/values.yaml
Labels: approved, size/XXL

#7 Revert "Revert "Revert "Revert "try realms""""
  charts/keycloak-http/files/bbd-realm.json
  charts/keycloak-http/files/external-realm.json
  charts/keycloak-http/files/master-realm.json
  charts/keycloak-http/templates/realm-secret.yaml
  charts/keycloak-http/values.yaml
Labels: approved, lgtm, size/XXL

#8 remove quote on secrets
  charts/keycloak-http/templates/realm-secret.yaml
Labels: approved, size/XS

#9 Separating ream secrets and explicit imports of each realm json.
  charts/keycloak-http/templates/realm-secret-bbd.yaml
  charts/keycloak-http/templates/realm-secret-external.yaml
  charts/keycloak-http/templates/realm-secret-master.yaml
  charts/keycloak-http/values.yaml
Labels: approved, size/M

#11 Pr get this working
  charts/keycloak-http/templates/realm-secret-bbd.yaml
  charts/keycloak-http/templates/realm-secret-external.yaml
  charts/keycloak-http/templates/realm-secret.yaml
  charts/keycloak-http/values.yaml
Labels: approved, size/M

#12 Add quote again but still with master not first
  charts/keycloak-http/templates/realm-secret.yaml
Labels: approved, size/XS
